// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usecase-service/usecase-service.proto

package usecase_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Robot struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Robot) Reset()         { *m = Robot{} }
func (m *Robot) String() string { return proto.CompactTextString(m) }
func (*Robot) ProtoMessage()    {}
func (*Robot) Descriptor() ([]byte, []int) {
	return fileDescriptor_usecase_service_7bd09fc0196cc6af, []int{0}
}
func (m *Robot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Robot.Unmarshal(m, b)
}
func (m *Robot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Robot.Marshal(b, m, deterministic)
}
func (dst *Robot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robot.Merge(dst, src)
}
func (m *Robot) XXX_Size() int {
	return xxx_messageInfo_Robot.Size(m)
}
func (m *Robot) XXX_DiscardUnknown() {
	xxx_messageInfo_Robot.DiscardUnknown(m)
}

var xxx_messageInfo_Robot proto.InternalMessageInfo

func (m *Robot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Status struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_usecase_service_7bd09fc0196cc6af, []int{1}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Action struct {
	Robot                *Robot   `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	NewValue             string   `protobuf:"bytes,2,opt,name=newValue,proto3" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_usecase_service_7bd09fc0196cc6af, []int{2}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetRobot() *Robot {
	if m != nil {
		return m.Robot
	}
	return nil
}

func (m *Action) GetNewValue() string {
	if m != nil {
		return m.NewValue
	}
	return ""
}

type IntParameter struct {
	Min                  int64    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int64    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Default              int64    `protobuf:"varint,3,opt,name=default,proto3" json:"default,omitempty"`
	Current              int64    `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntParameter) Reset()         { *m = IntParameter{} }
func (m *IntParameter) String() string { return proto.CompactTextString(m) }
func (*IntParameter) ProtoMessage()    {}
func (*IntParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_usecase_service_7bd09fc0196cc6af, []int{3}
}
func (m *IntParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntParameter.Unmarshal(m, b)
}
func (m *IntParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntParameter.Marshal(b, m, deterministic)
}
func (dst *IntParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntParameter.Merge(dst, src)
}
func (m *IntParameter) XXX_Size() int {
	return xxx_messageInfo_IntParameter.Size(m)
}
func (m *IntParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_IntParameter.DiscardUnknown(m)
}

var xxx_messageInfo_IntParameter proto.InternalMessageInfo

func (m *IntParameter) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *IntParameter) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *IntParameter) GetDefault() int64 {
	if m != nil {
		return m.Default
	}
	return 0
}

func (m *IntParameter) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

type BoolParameter struct {
	Default              bool     `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
	Current              bool     `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolParameter) Reset()         { *m = BoolParameter{} }
func (m *BoolParameter) String() string { return proto.CompactTextString(m) }
func (*BoolParameter) ProtoMessage()    {}
func (*BoolParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_usecase_service_7bd09fc0196cc6af, []int{4}
}
func (m *BoolParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolParameter.Unmarshal(m, b)
}
func (m *BoolParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolParameter.Marshal(b, m, deterministic)
}
func (dst *BoolParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolParameter.Merge(dst, src)
}
func (m *BoolParameter) XXX_Size() int {
	return xxx_messageInfo_BoolParameter.Size(m)
}
func (m *BoolParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolParameter.DiscardUnknown(m)
}

var xxx_messageInfo_BoolParameter proto.InternalMessageInfo

func (m *BoolParameter) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *BoolParameter) GetCurrent() bool {
	if m != nil {
		return m.Current
	}
	return false
}

type CalibrationParameter struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Details:
	//	*CalibrationParameter_IntParameter
	//	*CalibrationParameter_BoolParameter
	Details              isCalibrationParameter_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CalibrationParameter) Reset()         { *m = CalibrationParameter{} }
func (m *CalibrationParameter) String() string { return proto.CompactTextString(m) }
func (*CalibrationParameter) ProtoMessage()    {}
func (*CalibrationParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_usecase_service_7bd09fc0196cc6af, []int{5}
}
func (m *CalibrationParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalibrationParameter.Unmarshal(m, b)
}
func (m *CalibrationParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalibrationParameter.Marshal(b, m, deterministic)
}
func (dst *CalibrationParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalibrationParameter.Merge(dst, src)
}
func (m *CalibrationParameter) XXX_Size() int {
	return xxx_messageInfo_CalibrationParameter.Size(m)
}
func (m *CalibrationParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_CalibrationParameter.DiscardUnknown(m)
}

var xxx_messageInfo_CalibrationParameter proto.InternalMessageInfo

func (m *CalibrationParameter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CalibrationParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CalibrationParameter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type isCalibrationParameter_Details interface {
	isCalibrationParameter_Details()
}

type CalibrationParameter_IntParameter struct {
	IntParameter *IntParameter `protobuf:"bytes,4,opt,name=intParameter,proto3,oneof"`
}

type CalibrationParameter_BoolParameter struct {
	BoolParameter *BoolParameter `protobuf:"bytes,5,opt,name=boolParameter,proto3,oneof"`
}

func (*CalibrationParameter_IntParameter) isCalibrationParameter_Details() {}

func (*CalibrationParameter_BoolParameter) isCalibrationParameter_Details() {}

func (m *CalibrationParameter) GetDetails() isCalibrationParameter_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *CalibrationParameter) GetIntParameter() *IntParameter {
	if x, ok := m.GetDetails().(*CalibrationParameter_IntParameter); ok {
		return x.IntParameter
	}
	return nil
}

func (m *CalibrationParameter) GetBoolParameter() *BoolParameter {
	if x, ok := m.GetDetails().(*CalibrationParameter_BoolParameter); ok {
		return x.BoolParameter
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CalibrationParameter) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CalibrationParameter_OneofMarshaler, _CalibrationParameter_OneofUnmarshaler, _CalibrationParameter_OneofSizer, []interface{}{
		(*CalibrationParameter_IntParameter)(nil),
		(*CalibrationParameter_BoolParameter)(nil),
	}
}

func _CalibrationParameter_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CalibrationParameter)
	// details
	switch x := m.Details.(type) {
	case *CalibrationParameter_IntParameter:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IntParameter); err != nil {
			return err
		}
	case *CalibrationParameter_BoolParameter:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BoolParameter); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CalibrationParameter.Details has unexpected type %T", x)
	}
	return nil
}

func _CalibrationParameter_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CalibrationParameter)
	switch tag {
	case 4: // details.intParameter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IntParameter)
		err := b.DecodeMessage(msg)
		m.Details = &CalibrationParameter_IntParameter{msg}
		return true, err
	case 5: // details.boolParameter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BoolParameter)
		err := b.DecodeMessage(msg)
		m.Details = &CalibrationParameter_BoolParameter{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CalibrationParameter_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CalibrationParameter)
	// details
	switch x := m.Details.(type) {
	case *CalibrationParameter_IntParameter:
		s := proto.Size(x.IntParameter)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CalibrationParameter_BoolParameter:
		s := proto.Size(x.BoolParameter)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SetCalibrationParameterRequest struct {
	Robot *Robot `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Details:
	//	*SetCalibrationParameterRequest_IntValue
	//	*SetCalibrationParameterRequest_BoolValue
	Details              isSetCalibrationParameterRequest_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *SetCalibrationParameterRequest) Reset()         { *m = SetCalibrationParameterRequest{} }
func (m *SetCalibrationParameterRequest) String() string { return proto.CompactTextString(m) }
func (*SetCalibrationParameterRequest) ProtoMessage()    {}
func (*SetCalibrationParameterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usecase_service_7bd09fc0196cc6af, []int{6}
}
func (m *SetCalibrationParameterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCalibrationParameterRequest.Unmarshal(m, b)
}
func (m *SetCalibrationParameterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCalibrationParameterRequest.Marshal(b, m, deterministic)
}
func (dst *SetCalibrationParameterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCalibrationParameterRequest.Merge(dst, src)
}
func (m *SetCalibrationParameterRequest) XXX_Size() int {
	return xxx_messageInfo_SetCalibrationParameterRequest.Size(m)
}
func (m *SetCalibrationParameterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCalibrationParameterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCalibrationParameterRequest proto.InternalMessageInfo

func (m *SetCalibrationParameterRequest) GetRobot() *Robot {
	if m != nil {
		return m.Robot
	}
	return nil
}

func (m *SetCalibrationParameterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type isSetCalibrationParameterRequest_Details interface {
	isSetCalibrationParameterRequest_Details()
}

type SetCalibrationParameterRequest_IntValue struct {
	IntValue int64 `protobuf:"varint,4,opt,name=intValue,proto3,oneof"`
}

type SetCalibrationParameterRequest_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=boolValue,proto3,oneof"`
}

func (*SetCalibrationParameterRequest_IntValue) isSetCalibrationParameterRequest_Details() {}

func (*SetCalibrationParameterRequest_BoolValue) isSetCalibrationParameterRequest_Details() {}

func (m *SetCalibrationParameterRequest) GetDetails() isSetCalibrationParameterRequest_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *SetCalibrationParameterRequest) GetIntValue() int64 {
	if x, ok := m.GetDetails().(*SetCalibrationParameterRequest_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *SetCalibrationParameterRequest) GetBoolValue() bool {
	if x, ok := m.GetDetails().(*SetCalibrationParameterRequest_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SetCalibrationParameterRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SetCalibrationParameterRequest_OneofMarshaler, _SetCalibrationParameterRequest_OneofUnmarshaler, _SetCalibrationParameterRequest_OneofSizer, []interface{}{
		(*SetCalibrationParameterRequest_IntValue)(nil),
		(*SetCalibrationParameterRequest_BoolValue)(nil),
	}
}

func _SetCalibrationParameterRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SetCalibrationParameterRequest)
	// details
	switch x := m.Details.(type) {
	case *SetCalibrationParameterRequest_IntValue:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.IntValue))
	case *SetCalibrationParameterRequest_BoolValue:
		t := uint64(0)
		if x.BoolValue {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("SetCalibrationParameterRequest.Details has unexpected type %T", x)
	}
	return nil
}

func _SetCalibrationParameterRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SetCalibrationParameterRequest)
	switch tag {
	case 4: // details.intValue
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Details = &SetCalibrationParameterRequest_IntValue{int64(x)}
		return true, err
	case 5: // details.boolValue
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Details = &SetCalibrationParameterRequest_BoolValue{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _SetCalibrationParameterRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SetCalibrationParameterRequest)
	// details
	switch x := m.Details.(type) {
	case *SetCalibrationParameterRequest_IntValue:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.IntValue))
	case *SetCalibrationParameterRequest_BoolValue:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResetCalibrationParameterRequest struct {
	Robot                *Robot   `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetCalibrationParameterRequest) Reset()         { *m = ResetCalibrationParameterRequest{} }
func (m *ResetCalibrationParameterRequest) String() string { return proto.CompactTextString(m) }
func (*ResetCalibrationParameterRequest) ProtoMessage()    {}
func (*ResetCalibrationParameterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usecase_service_7bd09fc0196cc6af, []int{7}
}
func (m *ResetCalibrationParameterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetCalibrationParameterRequest.Unmarshal(m, b)
}
func (m *ResetCalibrationParameterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetCalibrationParameterRequest.Marshal(b, m, deterministic)
}
func (dst *ResetCalibrationParameterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetCalibrationParameterRequest.Merge(dst, src)
}
func (m *ResetCalibrationParameterRequest) XXX_Size() int {
	return xxx_messageInfo_ResetCalibrationParameterRequest.Size(m)
}
func (m *ResetCalibrationParameterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetCalibrationParameterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetCalibrationParameterRequest proto.InternalMessageInfo

func (m *ResetCalibrationParameterRequest) GetRobot() *Robot {
	if m != nil {
		return m.Robot
	}
	return nil
}

func (m *ResetCalibrationParameterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Robot)(nil), "Robot")
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*Action)(nil), "Action")
	proto.RegisterType((*IntParameter)(nil), "IntParameter")
	proto.RegisterType((*BoolParameter)(nil), "BoolParameter")
	proto.RegisterType((*CalibrationParameter)(nil), "CalibrationParameter")
	proto.RegisterType((*SetCalibrationParameterRequest)(nil), "SetCalibrationParameterRequest")
	proto.RegisterType((*ResetCalibrationParameterRequest)(nil), "ResetCalibrationParameterRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsecaseServerClient is the client API for UsecaseServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsecaseServerClient interface {
	// registers the robot with this usecase
	SetUsecase(ctx context.Context, in *Robot, opts ...grpc.CallOption) (*empty.Empty, error)
	GetStatus(ctx context.Context, in *Robot, opts ...grpc.CallOption) (*Status, error)
	SetRobot(ctx context.Context, in *Action, opts ...grpc.CallOption) (*empty.Empty, error)
	GetCalibrationParameters(ctx context.Context, in *Robot, opts ...grpc.CallOption) (UsecaseServer_GetCalibrationParametersClient, error)
	SetCalibrationParameter(ctx context.Context, in *SetCalibrationParameterRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// resets a calibration parameter to its default value
	ResetCalibrationParameter(ctx context.Context, in *ResetCalibrationParameterRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type usecaseServerClient struct {
	cc *grpc.ClientConn
}

func NewUsecaseServerClient(cc *grpc.ClientConn) UsecaseServerClient {
	return &usecaseServerClient{cc}
}

func (c *usecaseServerClient) SetUsecase(ctx context.Context, in *Robot, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/UsecaseServer/SetUsecase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usecaseServerClient) GetStatus(ctx context.Context, in *Robot, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/UsecaseServer/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usecaseServerClient) SetRobot(ctx context.Context, in *Action, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/UsecaseServer/SetRobot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usecaseServerClient) GetCalibrationParameters(ctx context.Context, in *Robot, opts ...grpc.CallOption) (UsecaseServer_GetCalibrationParametersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UsecaseServer_serviceDesc.Streams[0], "/UsecaseServer/GetCalibrationParameters", opts...)
	if err != nil {
		return nil, err
	}
	x := &usecaseServerGetCalibrationParametersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UsecaseServer_GetCalibrationParametersClient interface {
	Recv() (*CalibrationParameter, error)
	grpc.ClientStream
}

type usecaseServerGetCalibrationParametersClient struct {
	grpc.ClientStream
}

func (x *usecaseServerGetCalibrationParametersClient) Recv() (*CalibrationParameter, error) {
	m := new(CalibrationParameter)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *usecaseServerClient) SetCalibrationParameter(ctx context.Context, in *SetCalibrationParameterRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/UsecaseServer/SetCalibrationParameter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usecaseServerClient) ResetCalibrationParameter(ctx context.Context, in *ResetCalibrationParameterRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/UsecaseServer/ResetCalibrationParameter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsecaseServerServer is the server API for UsecaseServer service.
type UsecaseServerServer interface {
	// registers the robot with this usecase
	SetUsecase(context.Context, *Robot) (*empty.Empty, error)
	GetStatus(context.Context, *Robot) (*Status, error)
	SetRobot(context.Context, *Action) (*empty.Empty, error)
	GetCalibrationParameters(*Robot, UsecaseServer_GetCalibrationParametersServer) error
	SetCalibrationParameter(context.Context, *SetCalibrationParameterRequest) (*empty.Empty, error)
	// resets a calibration parameter to its default value
	ResetCalibrationParameter(context.Context, *ResetCalibrationParameterRequest) (*empty.Empty, error)
}

func RegisterUsecaseServerServer(s *grpc.Server, srv UsecaseServerServer) {
	s.RegisterService(&_UsecaseServer_serviceDesc, srv)
}

func _UsecaseServer_SetUsecase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Robot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsecaseServerServer).SetUsecase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsecaseServer/SetUsecase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsecaseServerServer).SetUsecase(ctx, req.(*Robot))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsecaseServer_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Robot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsecaseServerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsecaseServer/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsecaseServerServer).GetStatus(ctx, req.(*Robot))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsecaseServer_SetRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsecaseServerServer).SetRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsecaseServer/SetRobot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsecaseServerServer).SetRobot(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsecaseServer_GetCalibrationParameters_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Robot)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UsecaseServerServer).GetCalibrationParameters(m, &usecaseServerGetCalibrationParametersServer{stream})
}

type UsecaseServer_GetCalibrationParametersServer interface {
	Send(*CalibrationParameter) error
	grpc.ServerStream
}

type usecaseServerGetCalibrationParametersServer struct {
	grpc.ServerStream
}

func (x *usecaseServerGetCalibrationParametersServer) Send(m *CalibrationParameter) error {
	return x.ServerStream.SendMsg(m)
}

func _UsecaseServer_SetCalibrationParameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCalibrationParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsecaseServerServer).SetCalibrationParameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsecaseServer/SetCalibrationParameter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsecaseServerServer).SetCalibrationParameter(ctx, req.(*SetCalibrationParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsecaseServer_ResetCalibrationParameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetCalibrationParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsecaseServerServer).ResetCalibrationParameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UsecaseServer/ResetCalibrationParameter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsecaseServerServer).ResetCalibrationParameter(ctx, req.(*ResetCalibrationParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsecaseServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UsecaseServer",
	HandlerType: (*UsecaseServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUsecase",
			Handler:    _UsecaseServer_SetUsecase_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _UsecaseServer_GetStatus_Handler,
		},
		{
			MethodName: "SetRobot",
			Handler:    _UsecaseServer_SetRobot_Handler,
		},
		{
			MethodName: "SetCalibrationParameter",
			Handler:    _UsecaseServer_SetCalibrationParameter_Handler,
		},
		{
			MethodName: "ResetCalibrationParameter",
			Handler:    _UsecaseServer_ResetCalibrationParameter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCalibrationParameters",
			Handler:       _UsecaseServer_GetCalibrationParameters_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "usecase-service/usecase-service.proto",
}

func init() {
	proto.RegisterFile("usecase-service/usecase-service.proto", fileDescriptor_usecase_service_7bd09fc0196cc6af)
}

var fileDescriptor_usecase_service_7bd09fc0196cc6af = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x4d, 0xd2, 0xb5, 0x4d, 0xef, 0xd6, 0x09, 0x59, 0x83, 0x85, 0x32, 0x95, 0x11, 0x09, 0x89,
	0x97, 0xb9, 0xa8, 0x93, 0x78, 0xe3, 0x81, 0x4e, 0x68, 0xe5, 0x6d, 0x72, 0x00, 0xf1, 0xea, 0xb4,
	0xb7, 0x53, 0xa4, 0x34, 0x2e, 0x8e, 0x53, 0xb6, 0x5f, 0xc2, 0x3f, 0xe2, 0x5f, 0x21, 0x21, 0xdb,
	0x49, 0x9b, 0x4e, 0xfd, 0x78, 0xe1, 0xcd, 0xf7, 0x1c, 0xfb, 0xf8, 0x9c, 0x7b, 0x75, 0xe1, 0x6d,
	0x91, 0xe3, 0x84, 0xe7, 0x78, 0x95, 0xa3, 0x5c, 0x26, 0x13, 0x1c, 0x3c, 0xa9, 0xe9, 0x42, 0x0a,
	0x25, 0x7a, 0xaf, 0xee, 0x85, 0xb8, 0x4f, 0x71, 0x60, 0xaa, 0xb8, 0x98, 0x0d, 0x70, 0xbe, 0x50,
	0x8f, 0x96, 0x0c, 0xcf, 0xa1, 0xc9, 0x44, 0x2c, 0x14, 0x39, 0x05, 0x2f, 0x99, 0x06, 0xee, 0xa5,
	0xfb, 0xae, 0xc3, 0xbc, 0x64, 0x1a, 0xf6, 0xa1, 0x15, 0x29, 0xae, 0x8a, 0x9c, 0x9c, 0x41, 0x73,
	0xc9, 0xd3, 0x02, 0x4b, 0xd2, 0x16, 0xe1, 0x08, 0x5a, 0x9f, 0x26, 0x2a, 0x11, 0x19, 0xb9, 0x80,
	0xa6, 0xd4, 0x12, 0x86, 0x3f, 0x1e, 0xb6, 0xa8, 0x11, 0x64, 0x16, 0x24, 0x3d, 0xf0, 0x33, 0xfc,
	0xf5, 0xdd, 0x08, 0x78, 0x46, 0x60, 0x55, 0x87, 0x33, 0x38, 0xf9, 0x92, 0xa9, 0x3b, 0x2e, 0xf9,
	0x1c, 0x15, 0x4a, 0xf2, 0x0c, 0x1a, 0xf3, 0x24, 0x33, 0x3a, 0x0d, 0xa6, 0x8f, 0x06, 0xe1, 0x0f,
	0xe6, 0xa1, 0x46, 0xf8, 0x03, 0x09, 0xa0, 0x3d, 0xc5, 0x19, 0x2f, 0x52, 0x15, 0x34, 0x0c, 0x5a,
	0x95, 0x9a, 0x99, 0x14, 0x52, 0x62, 0xa6, 0x82, 0x23, 0xcb, 0x94, 0x65, 0x78, 0x03, 0xdd, 0x91,
	0x10, 0xe9, 0xfa, 0xa3, 0x9a, 0x88, 0xfe, 0xcc, 0xdf, 0x2a, 0xe2, 0x59, 0xa6, 0x12, 0xf9, 0xe3,
	0xc2, 0xd9, 0x0d, 0x4f, 0x93, 0x58, 0x72, 0x1d, 0x7b, 0x2d, 0xf6, 0xa4, 0x73, 0x84, 0xc0, 0x51,
	0xc6, 0xe7, 0x55, 0x5a, 0x73, 0xd6, 0x98, 0x7a, 0x5c, 0xa0, 0xb1, 0xdc, 0x61, 0xe6, 0x4c, 0xae,
	0xe1, 0x24, 0xa9, 0xa5, 0x37, 0xa6, 0x8f, 0x87, 0x5d, 0x5a, 0x6f, 0xc9, 0xd8, 0x61, 0x1b, 0x97,
	0xc8, 0x07, 0xe8, 0xc6, 0xf5, 0x28, 0x41, 0xd3, 0xbc, 0x3a, 0xa5, 0x1b, 0x01, 0xc7, 0x0e, 0xdb,
	0xbc, 0x36, 0xea, 0xe8, 0xc4, 0x8a, 0x27, 0x69, 0x1e, 0xfe, 0x76, 0xa1, 0x1f, 0xa1, 0xda, 0x96,
	0x85, 0xe1, 0xcf, 0x02, 0x73, 0x75, 0x60, 0xa4, 0x36, 0xb0, 0xb7, 0x0a, 0x7c, 0x01, 0x7e, 0x92,
	0x29, 0x3b, 0x62, 0xd3, 0xf9, 0xb1, 0xc3, 0x56, 0x08, 0xe9, 0x43, 0x47, 0x5b, 0xb1, 0xb4, 0x76,
	0xeb, 0x8f, 0x1d, 0xb6, 0x86, 0xea, 0xce, 0xee, 0xe0, 0x92, 0x61, 0xfe, 0x1f, 0xad, 0x0d, 0xff,
	0x7a, 0xd0, 0xfd, 0x66, 0xb7, 0x22, 0x42, 0xb9, 0x44, 0x49, 0x28, 0x40, 0x84, 0xaa, 0xc4, 0x48,
	0xf9, 0xbc, 0xf7, 0x82, 0xda, 0x25, 0xa1, 0xd5, 0x92, 0xd0, 0xcf, 0x7a, 0x49, 0x42, 0x47, 0xdb,
	0xbf, 0x45, 0x55, 0xae, 0x42, 0x75, 0xbd, 0x4d, 0x2d, 0x10, 0x3a, 0xe4, 0x0a, 0xfc, 0x08, 0x95,
	0xdd, 0xa1, 0x36, 0xb5, 0x2b, 0xb1, 0x47, 0xee, 0x23, 0x04, 0xb7, 0xdb, 0x03, 0xae, 0xd5, 0x9f,
	0xd3, 0x6d, 0x7c, 0xe8, 0xbc, 0x77, 0xc9, 0x57, 0x38, 0xdf, 0x31, 0x3a, 0xf2, 0x9a, 0xee, 0x1f,
	0xea, 0x1e, 0x53, 0x3f, 0xe0, 0xe5, 0xce, 0xbe, 0x93, 0x37, 0xf4, 0xd0, 0x4c, 0x76, 0x2b, 0xc7,
	0x2d, 0x83, 0x5c, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x22, 0x63, 0xad, 0xd5, 0xab, 0x04, 0x00,
	0x00,
}
