// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thermostatserver/thermostatserver.proto

package thermostatserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ThermostatServerClient is the client API for ThermostatServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ThermostatServerClient interface {
}

type thermostatServerClient struct {
	cc *grpc.ClientConn
}

func NewThermostatServerClient(cc *grpc.ClientConn) ThermostatServerClient {
	return &thermostatServerClient{cc}
}

// ThermostatServerServer is the server API for ThermostatServer service.
type ThermostatServerServer interface {
}

func RegisterThermostatServerServer(s *grpc.Server, srv ThermostatServerServer) {
	s.RegisterService(&_ThermostatServer_serviceDesc, srv)
}

var _ThermostatServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ThermostatServer",
	HandlerType: (*ThermostatServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "thermostatserver/thermostatserver.proto",
}

func init() {
	proto.RegisterFile("thermostatserver/thermostatserver.proto", fileDescriptor_thermostatserver_86a0c58c04c4d332)
}

var fileDescriptor_thermostatserver_86a0c58c04c4d332 = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0xc9, 0x48, 0x2d,
	0xca, 0xcd, 0x2f, 0x2e, 0x49, 0x2c, 0x29, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x47, 0x17, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xf3,
	0x92, 0x4a, 0xd3, 0xf4, 0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0x92, 0x46, 0x42, 0x5c, 0x02, 0x21,
	0x70, 0x6d, 0xc1, 0x60, 0x6d, 0x49, 0x6c, 0x60, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x2f, 0xa6, 0x67, 0xd4, 0x62, 0x00, 0x00, 0x00,
}
