// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infoserver/infoserver.proto

package infoserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RobotQuery struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotQuery) Reset()         { *m = RobotQuery{} }
func (m *RobotQuery) String() string { return proto.CompactTextString(m) }
func (*RobotQuery) ProtoMessage()    {}
func (*RobotQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_infoserver_8304aa0039e2df26, []int{0}
}
func (m *RobotQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotQuery.Unmarshal(m, b)
}
func (m *RobotQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotQuery.Marshal(b, m, deterministic)
}
func (dst *RobotQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotQuery.Merge(dst, src)
}
func (m *RobotQuery) XXX_Size() int {
	return xxx_messageInfo_RobotQuery.Size(m)
}
func (m *RobotQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RobotQuery proto.InternalMessageInfo

func (m *RobotQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Robot struct {
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	RobotType     string `protobuf:"bytes,3,opt,name=robotType,proto3" json:"robotType,omitempty"`
	InterfaceType string `protobuf:"bytes,4,opt,name=interfaceType,proto3" json:"interfaceType,omitempty"`
	// Types that are valid to be assigned to RobotStatus:
	//	*Robot_ToggleStatus
	//	*Robot_RangeStatus
	RobotStatus          isRobot_RobotStatus `protobuf_oneof:"robotStatus"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Robot) Reset()         { *m = Robot{} }
func (m *Robot) String() string { return proto.CompactTextString(m) }
func (*Robot) ProtoMessage()    {}
func (*Robot) Descriptor() ([]byte, []int) {
	return fileDescriptor_infoserver_8304aa0039e2df26, []int{1}
}
func (m *Robot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Robot.Unmarshal(m, b)
}
func (m *Robot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Robot.Marshal(b, m, deterministic)
}
func (dst *Robot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Robot.Merge(dst, src)
}
func (m *Robot) XXX_Size() int {
	return xxx_messageInfo_Robot.Size(m)
}
func (m *Robot) XXX_DiscardUnknown() {
	xxx_messageInfo_Robot.DiscardUnknown(m)
}

var xxx_messageInfo_Robot proto.InternalMessageInfo

func (m *Robot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Robot) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Robot) GetRobotType() string {
	if m != nil {
		return m.RobotType
	}
	return ""
}

func (m *Robot) GetInterfaceType() string {
	if m != nil {
		return m.InterfaceType
	}
	return ""
}

type isRobot_RobotStatus interface {
	isRobot_RobotStatus()
}

type Robot_ToggleStatus struct {
	ToggleStatus *ToggleStatus `protobuf:"bytes,5,opt,name=toggleStatus,proto3,oneof"`
}

type Robot_RangeStatus struct {
	RangeStatus *RangeStatus `protobuf:"bytes,6,opt,name=rangeStatus,proto3,oneof"`
}

func (*Robot_ToggleStatus) isRobot_RobotStatus() {}

func (*Robot_RangeStatus) isRobot_RobotStatus() {}

func (m *Robot) GetRobotStatus() isRobot_RobotStatus {
	if m != nil {
		return m.RobotStatus
	}
	return nil
}

func (m *Robot) GetToggleStatus() *ToggleStatus {
	if x, ok := m.GetRobotStatus().(*Robot_ToggleStatus); ok {
		return x.ToggleStatus
	}
	return nil
}

func (m *Robot) GetRangeStatus() *RangeStatus {
	if x, ok := m.GetRobotStatus().(*Robot_RangeStatus); ok {
		return x.RangeStatus
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Robot) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Robot_OneofMarshaler, _Robot_OneofUnmarshaler, _Robot_OneofSizer, []interface{}{
		(*Robot_ToggleStatus)(nil),
		(*Robot_RangeStatus)(nil),
	}
}

func _Robot_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Robot)
	// robotStatus
	switch x := m.RobotStatus.(type) {
	case *Robot_ToggleStatus:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ToggleStatus); err != nil {
			return err
		}
	case *Robot_RangeStatus:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RangeStatus); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Robot.RobotStatus has unexpected type %T", x)
	}
	return nil
}

func _Robot_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Robot)
	switch tag {
	case 5: // robotStatus.toggleStatus
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ToggleStatus)
		err := b.DecodeMessage(msg)
		m.RobotStatus = &Robot_ToggleStatus{msg}
		return true, err
	case 6: // robotStatus.rangeStatus
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RangeStatus)
		err := b.DecodeMessage(msg)
		m.RobotStatus = &Robot_RangeStatus{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Robot_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Robot)
	// robotStatus
	switch x := m.RobotStatus.(type) {
	case *Robot_ToggleStatus:
		s := proto.Size(x.ToggleStatus)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Robot_RangeStatus:
		s := proto.Size(x.RangeStatus)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ToggleStatus struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleStatus) Reset()         { *m = ToggleStatus{} }
func (m *ToggleStatus) String() string { return proto.CompactTextString(m) }
func (*ToggleStatus) ProtoMessage()    {}
func (*ToggleStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_infoserver_8304aa0039e2df26, []int{2}
}
func (m *ToggleStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToggleStatus.Unmarshal(m, b)
}
func (m *ToggleStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToggleStatus.Marshal(b, m, deterministic)
}
func (dst *ToggleStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleStatus.Merge(dst, src)
}
func (m *ToggleStatus) XXX_Size() int {
	return xxx_messageInfo_ToggleStatus.Size(m)
}
func (m *ToggleStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleStatus proto.InternalMessageInfo

func (m *ToggleStatus) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type RangeStatus struct {
	Max                  int64    `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Min                  int64    `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Current              int64    `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RangeStatus) Reset()         { *m = RangeStatus{} }
func (m *RangeStatus) String() string { return proto.CompactTextString(m) }
func (*RangeStatus) ProtoMessage()    {}
func (*RangeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_infoserver_8304aa0039e2df26, []int{3}
}
func (m *RangeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeStatus.Unmarshal(m, b)
}
func (m *RangeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeStatus.Marshal(b, m, deterministic)
}
func (dst *RangeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeStatus.Merge(dst, src)
}
func (m *RangeStatus) XXX_Size() int {
	return xxx_messageInfo_RangeStatus.Size(m)
}
func (m *RangeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RangeStatus proto.InternalMessageInfo

func (m *RangeStatus) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *RangeStatus) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *RangeStatus) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterType((*RobotQuery)(nil), "RobotQuery")
	proto.RegisterType((*Robot)(nil), "Robot")
	proto.RegisterType((*ToggleStatus)(nil), "ToggleStatus")
	proto.RegisterType((*RangeStatus)(nil), "RangeStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InfoServerClient is the client API for InfoServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfoServerClient interface {
	GetRobot(ctx context.Context, in *RobotQuery, opts ...grpc.CallOption) (*Robot, error)
	GetRobots(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (InfoServer_GetRobotsClient, error)
}

type infoServerClient struct {
	cc *grpc.ClientConn
}

func NewInfoServerClient(cc *grpc.ClientConn) InfoServerClient {
	return &infoServerClient{cc}
}

func (c *infoServerClient) GetRobot(ctx context.Context, in *RobotQuery, opts ...grpc.CallOption) (*Robot, error) {
	out := new(Robot)
	err := c.cc.Invoke(ctx, "/InfoServer/GetRobot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServerClient) GetRobots(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (InfoServer_GetRobotsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InfoServer_serviceDesc.Streams[0], "/InfoServer/GetRobots", opts...)
	if err != nil {
		return nil, err
	}
	x := &infoServerGetRobotsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InfoServer_GetRobotsClient interface {
	Recv() (*Robot, error)
	grpc.ClientStream
}

type infoServerGetRobotsClient struct {
	grpc.ClientStream
}

func (x *infoServerGetRobotsClient) Recv() (*Robot, error) {
	m := new(Robot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InfoServerServer is the server API for InfoServer service.
type InfoServerServer interface {
	GetRobot(context.Context, *RobotQuery) (*Robot, error)
	GetRobots(*empty.Empty, InfoServer_GetRobotsServer) error
}

func RegisterInfoServerServer(s *grpc.Server, srv InfoServerServer) {
	s.RegisterService(&_InfoServer_serviceDesc, srv)
}

func _InfoServer_GetRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServerServer).GetRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InfoServer/GetRobot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServerServer).GetRobot(ctx, req.(*RobotQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoServer_GetRobots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InfoServerServer).GetRobots(m, &infoServerGetRobotsServer{stream})
}

type InfoServer_GetRobotsServer interface {
	Send(*Robot) error
	grpc.ServerStream
}

type infoServerGetRobotsServer struct {
	grpc.ServerStream
}

func (x *infoServerGetRobotsServer) Send(m *Robot) error {
	return x.ServerStream.SendMsg(m)
}

var _InfoServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "InfoServer",
	HandlerType: (*InfoServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRobot",
			Handler:    _InfoServer_GetRobot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRobots",
			Handler:       _InfoServer_GetRobots_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "infoserver/infoserver.proto",
}

func init() {
	proto.RegisterFile("infoserver/infoserver.proto", fileDescriptor_infoserver_8304aa0039e2df26)
}

var fileDescriptor_infoserver_8304aa0039e2df26 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdd, 0x4e, 0xc2, 0x40,
	0x10, 0x85, 0x29, 0x15, 0x84, 0x29, 0x18, 0xb3, 0x31, 0xa6, 0x01, 0x2e, 0xb0, 0xe1, 0x82, 0xab,
	0x2d, 0x81, 0x37, 0x30, 0x31, 0x62, 0xbc, 0x72, 0xe1, 0x01, 0x2c, 0x30, 0x6d, 0x36, 0xc2, 0x2e,
	0x59, 0xb6, 0x44, 0x1e, 0xda, 0x77, 0x30, 0x9d, 0x4d, 0x6d, 0xf1, 0x6e, 0xce, 0x39, 0xdf, 0xf4,
	0x67, 0x0e, 0x0c, 0xa5, 0x4a, 0xf5, 0x09, 0xcd, 0x19, 0x4d, 0x5c, 0x8d, 0xfc, 0x68, 0xb4, 0xd5,
	0x83, 0x61, 0xa6, 0x75, 0xb6, 0xc7, 0x98, 0xd4, 0x26, 0x4f, 0x63, 0x3c, 0x1c, 0xed, 0xc5, 0x85,
	0xd1, 0x08, 0x40, 0xe8, 0x8d, 0xb6, 0x1f, 0x39, 0x9a, 0x0b, 0xbb, 0x83, 0xa6, 0xdc, 0x85, 0xde,
	0xd8, 0x9b, 0x76, 0x45, 0x53, 0xee, 0xa2, 0x1f, 0x0f, 0x5a, 0x14, 0xff, 0x4f, 0xd8, 0x00, 0x3a,
	0x4a, 0x6e, 0xbf, 0x54, 0x72, 0xc0, 0xb0, 0x49, 0xee, 0x9f, 0x66, 0x23, 0xe8, 0x9a, 0x62, 0x69,
	0x7d, 0x39, 0x62, 0xe8, 0x53, 0x58, 0x19, 0x6c, 0x02, 0x7d, 0xa9, 0x2c, 0x9a, 0x34, 0xd9, 0x22,
	0x11, 0x37, 0x44, 0x5c, 0x9b, 0x6c, 0x01, 0x3d, 0xab, 0xb3, 0x6c, 0x8f, 0x2b, 0x9b, 0xd8, 0xfc,
	0x14, 0xb6, 0xc6, 0xde, 0x34, 0x98, 0xf7, 0xf9, 0xba, 0x66, 0x2e, 0x1b, 0xe2, 0x0a, 0x62, 0x33,
	0x08, 0x4c, 0xa2, 0xb2, 0x72, 0xa7, 0x4d, 0x3b, 0x3d, 0x2e, 0x2a, 0x6f, 0xd9, 0x10, 0x75, 0xe4,
	0xb9, 0x0f, 0x01, 0x7d, 0x99, 0x93, 0xd1, 0x04, 0x7a, 0xf5, 0x17, 0xb0, 0x07, 0x68, 0x9d, 0x93,
	0x7d, 0x8e, 0xf4, 0xe3, 0x1d, 0xe1, 0x44, 0xf4, 0x0e, 0x41, 0xed, 0x91, 0xec, 0x1e, 0xfc, 0x43,
	0xf2, 0x4d, 0x88, 0x2f, 0x8a, 0x91, 0x1c, 0xa9, 0xe8, 0x2e, 0x85, 0x23, 0x15, 0x0b, 0xe1, 0x76,
	0x9b, 0x1b, 0x83, 0xca, 0xd2, 0x41, 0x7c, 0x51, 0xca, 0xf9, 0x27, 0xc0, 0x9b, 0x4a, 0xf5, 0x8a,
	0x1a, 0x63, 0x4f, 0xd0, 0x79, 0x45, 0xeb, 0x4e, 0x1e, 0xf0, 0xaa, 0x99, 0x41, 0xdb, 0x89, 0xa8,
	0xc1, 0x62, 0xe8, 0x96, 0xc8, 0x89, 0x3d, 0x72, 0x57, 0x2e, 0x2f, 0xcb, 0xe5, 0x2f, 0x45, 0xb9,
	0x15, 0x3e, 0xf3, 0x36, 0x6d, 0xca, 0x16, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0xf0, 0x15,
	0x9d, 0x25, 0x02, 0x00, 0x00,
}
