// Code generated by protoc-gen-go. DO NOT EDIT.
// source: boltlockserver/boltlockserver.proto

package boltlockserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetBoltlockStatus_Status int32

const (
	SetBoltlockStatus_SETTING   SetBoltlockStatus_Status = 0
	SetBoltlockStatus_WAITING   SetBoltlockStatus_Status = 1
	SetBoltlockStatus_RETURNING SetBoltlockStatus_Status = 2
	SetBoltlockStatus_DONE      SetBoltlockStatus_Status = 3
)

var SetBoltlockStatus_Status_name = map[int32]string{
	0: "SETTING",
	1: "WAITING",
	2: "RETURNING",
	3: "DONE",
}

var SetBoltlockStatus_Status_value = map[string]int32{
	"SETTING":   0,
	"WAITING":   1,
	"RETURNING": 2,
	"DONE":      3,
}

func (x SetBoltlockStatus_Status) String() string {
	return proto.EnumName(SetBoltlockStatus_Status_name, int32(x))
}

func (SetBoltlockStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_27904a3d151073a4, []int{5, 0}
}

type Boltlock struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsOn                 bool     `protobuf:"varint,2,opt,name=isOn,proto3" json:"isOn,omitempty"`
	OnAngle              int64    `protobuf:"varint,3,opt,name=onAngle,proto3" json:"onAngle,omitempty"`
	OffAngle             int64    `protobuf:"varint,4,opt,name=offAngle,proto3" json:"offAngle,omitempty"`
	IsCalibrated         bool     `protobuf:"varint,5,opt,name=isCalibrated,proto3" json:"isCalibrated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Boltlock) Reset()         { *m = Boltlock{} }
func (m *Boltlock) String() string { return proto.CompactTextString(m) }
func (*Boltlock) ProtoMessage()    {}
func (*Boltlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_27904a3d151073a4, []int{0}
}

func (m *Boltlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Boltlock.Unmarshal(m, b)
}
func (m *Boltlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Boltlock.Marshal(b, m, deterministic)
}
func (m *Boltlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Boltlock.Merge(m, src)
}
func (m *Boltlock) XXX_Size() int {
	return xxx_messageInfo_Boltlock.Size(m)
}
func (m *Boltlock) XXX_DiscardUnknown() {
	xxx_messageInfo_Boltlock.DiscardUnknown(m)
}

var xxx_messageInfo_Boltlock proto.InternalMessageInfo

func (m *Boltlock) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Boltlock) GetIsOn() bool {
	if m != nil {
		return m.IsOn
	}
	return false
}

func (m *Boltlock) GetOnAngle() int64 {
	if m != nil {
		return m.OnAngle
	}
	return 0
}

func (m *Boltlock) GetOffAngle() int64 {
	if m != nil {
		return m.OffAngle
	}
	return 0
}

func (m *Boltlock) GetIsCalibrated() bool {
	if m != nil {
		return m.IsCalibrated
	}
	return false
}

type AddBoltlockRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsOn                 bool     `protobuf:"varint,2,opt,name=isOn,proto3" json:"isOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBoltlockRequest) Reset()         { *m = AddBoltlockRequest{} }
func (m *AddBoltlockRequest) String() string { return proto.CompactTextString(m) }
func (*AddBoltlockRequest) ProtoMessage()    {}
func (*AddBoltlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27904a3d151073a4, []int{1}
}

func (m *AddBoltlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBoltlockRequest.Unmarshal(m, b)
}
func (m *AddBoltlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBoltlockRequest.Marshal(b, m, deterministic)
}
func (m *AddBoltlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBoltlockRequest.Merge(m, src)
}
func (m *AddBoltlockRequest) XXX_Size() int {
	return xxx_messageInfo_AddBoltlockRequest.Size(m)
}
func (m *AddBoltlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBoltlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBoltlockRequest proto.InternalMessageInfo

func (m *AddBoltlockRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddBoltlockRequest) GetIsOn() bool {
	if m != nil {
		return m.IsOn
	}
	return false
}

type RemoveBoltlockRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveBoltlockRequest) Reset()         { *m = RemoveBoltlockRequest{} }
func (m *RemoveBoltlockRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveBoltlockRequest) ProtoMessage()    {}
func (*RemoveBoltlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27904a3d151073a4, []int{2}
}

func (m *RemoveBoltlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveBoltlockRequest.Unmarshal(m, b)
}
func (m *RemoveBoltlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveBoltlockRequest.Marshal(b, m, deterministic)
}
func (m *RemoveBoltlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveBoltlockRequest.Merge(m, src)
}
func (m *RemoveBoltlockRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveBoltlockRequest.Size(m)
}
func (m *RemoveBoltlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveBoltlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveBoltlockRequest proto.InternalMessageInfo

func (m *RemoveBoltlockRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BoltlockQuery struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoltlockQuery) Reset()         { *m = BoltlockQuery{} }
func (m *BoltlockQuery) String() string { return proto.CompactTextString(m) }
func (*BoltlockQuery) ProtoMessage()    {}
func (*BoltlockQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_27904a3d151073a4, []int{3}
}

func (m *BoltlockQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoltlockQuery.Unmarshal(m, b)
}
func (m *BoltlockQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoltlockQuery.Marshal(b, m, deterministic)
}
func (m *BoltlockQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoltlockQuery.Merge(m, src)
}
func (m *BoltlockQuery) XXX_Size() int {
	return xxx_messageInfo_BoltlockQuery.Size(m)
}
func (m *BoltlockQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_BoltlockQuery.DiscardUnknown(m)
}

var xxx_messageInfo_BoltlockQuery proto.InternalMessageInfo

func (m *BoltlockQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SetBoltlockRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	On                   bool     `protobuf:"varint,2,opt,name=on,proto3" json:"on,omitempty"`
	Force                bool     `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetBoltlockRequest) Reset()         { *m = SetBoltlockRequest{} }
func (m *SetBoltlockRequest) String() string { return proto.CompactTextString(m) }
func (*SetBoltlockRequest) ProtoMessage()    {}
func (*SetBoltlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27904a3d151073a4, []int{4}
}

func (m *SetBoltlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBoltlockRequest.Unmarshal(m, b)
}
func (m *SetBoltlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBoltlockRequest.Marshal(b, m, deterministic)
}
func (m *SetBoltlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBoltlockRequest.Merge(m, src)
}
func (m *SetBoltlockRequest) XXX_Size() int {
	return xxx_messageInfo_SetBoltlockRequest.Size(m)
}
func (m *SetBoltlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBoltlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetBoltlockRequest proto.InternalMessageInfo

func (m *SetBoltlockRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetBoltlockRequest) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

func (m *SetBoltlockRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type SetBoltlockStatus struct {
	Status               SetBoltlockStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=SetBoltlockStatus_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SetBoltlockStatus) Reset()         { *m = SetBoltlockStatus{} }
func (m *SetBoltlockStatus) String() string { return proto.CompactTextString(m) }
func (*SetBoltlockStatus) ProtoMessage()    {}
func (*SetBoltlockStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_27904a3d151073a4, []int{5}
}

func (m *SetBoltlockStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetBoltlockStatus.Unmarshal(m, b)
}
func (m *SetBoltlockStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetBoltlockStatus.Marshal(b, m, deterministic)
}
func (m *SetBoltlockStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetBoltlockStatus.Merge(m, src)
}
func (m *SetBoltlockStatus) XXX_Size() int {
	return xxx_messageInfo_SetBoltlockStatus.Size(m)
}
func (m *SetBoltlockStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SetBoltlockStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SetBoltlockStatus proto.InternalMessageInfo

func (m *SetBoltlockStatus) GetStatus() SetBoltlockStatus_Status {
	if m != nil {
		return m.Status
	}
	return SetBoltlockStatus_SETTING
}

type BoltlockCalibrationParameters struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OnAngle              *wrappers.Int64Value `protobuf:"bytes,2,opt,name=onAngle,proto3" json:"onAngle,omitempty"`
	OffAngle             *wrappers.Int64Value `protobuf:"bytes,3,opt,name=offAngle,proto3" json:"offAngle,omitempty"`
	IsCalibrated         *wrappers.BoolValue  `protobuf:"bytes,4,opt,name=isCalibrated,proto3" json:"isCalibrated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BoltlockCalibrationParameters) Reset()         { *m = BoltlockCalibrationParameters{} }
func (m *BoltlockCalibrationParameters) String() string { return proto.CompactTextString(m) }
func (*BoltlockCalibrationParameters) ProtoMessage()    {}
func (*BoltlockCalibrationParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_27904a3d151073a4, []int{6}
}

func (m *BoltlockCalibrationParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoltlockCalibrationParameters.Unmarshal(m, b)
}
func (m *BoltlockCalibrationParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoltlockCalibrationParameters.Marshal(b, m, deterministic)
}
func (m *BoltlockCalibrationParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoltlockCalibrationParameters.Merge(m, src)
}
func (m *BoltlockCalibrationParameters) XXX_Size() int {
	return xxx_messageInfo_BoltlockCalibrationParameters.Size(m)
}
func (m *BoltlockCalibrationParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_BoltlockCalibrationParameters.DiscardUnknown(m)
}

var xxx_messageInfo_BoltlockCalibrationParameters proto.InternalMessageInfo

func (m *BoltlockCalibrationParameters) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BoltlockCalibrationParameters) GetOnAngle() *wrappers.Int64Value {
	if m != nil {
		return m.OnAngle
	}
	return nil
}

func (m *BoltlockCalibrationParameters) GetOffAngle() *wrappers.Int64Value {
	if m != nil {
		return m.OffAngle
	}
	return nil
}

func (m *BoltlockCalibrationParameters) GetIsCalibrated() *wrappers.BoolValue {
	if m != nil {
		return m.IsCalibrated
	}
	return nil
}

func init() {
	proto.RegisterEnum("SetBoltlockStatus_Status", SetBoltlockStatus_Status_name, SetBoltlockStatus_Status_value)
	proto.RegisterType((*Boltlock)(nil), "Boltlock")
	proto.RegisterType((*AddBoltlockRequest)(nil), "AddBoltlockRequest")
	proto.RegisterType((*RemoveBoltlockRequest)(nil), "RemoveBoltlockRequest")
	proto.RegisterType((*BoltlockQuery)(nil), "BoltlockQuery")
	proto.RegisterType((*SetBoltlockRequest)(nil), "SetBoltlockRequest")
	proto.RegisterType((*SetBoltlockStatus)(nil), "SetBoltlockStatus")
	proto.RegisterType((*BoltlockCalibrationParameters)(nil), "BoltlockCalibrationParameters")
}

func init() {
	proto.RegisterFile("boltlockserver/boltlockserver.proto", fileDescriptor_27904a3d151073a4)
}

var fileDescriptor_27904a3d151073a4 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0xd2, 0xae, 0x6b, 0x6f, 0x58, 0xb4, 0xdd, 0xc1, 0x14, 0x32, 0x31, 0x2a, 0xf3, 0x40,
	0xc5, 0x83, 0x0b, 0xe5, 0x53, 0x20, 0x21, 0xb5, 0x50, 0x4d, 0x45, 0xa2, 0x03, 0xb7, 0xc0, 0x73,
	0xba, 0xb8, 0x55, 0x44, 0x1a, 0x17, 0xc7, 0x19, 0xda, 0x33, 0x2f, 0xfc, 0x28, 0xfe, 0x0b, 0x7f,
	0x05, 0xd5, 0x69, 0xda, 0x66, 0x01, 0xba, 0xa7, 0xf8, 0xf8, 0xde, 0x7b, 0x72, 0xec, 0x73, 0x0c,
	0xf7, 0xc6, 0x22, 0x54, 0xa1, 0x38, 0xff, 0x1a, 0x73, 0x79, 0xc1, 0x65, 0x2b, 0x0f, 0xe9, 0x5c,
	0x0a, 0x25, 0xdc, 0xe3, 0xa9, 0x10, 0xd3, 0x90, 0xb7, 0x34, 0x1a, 0x27, 0x93, 0x16, 0x9f, 0xcd,
	0xd5, 0xe5, 0xb2, 0x78, 0x72, 0xb5, 0xf8, 0x5d, 0x7a, 0xf3, 0x39, 0x97, 0x71, 0x5a, 0x27, 0x3f,
	0x0d, 0xa8, 0x75, 0x97, 0xac, 0x68, 0x83, 0x19, 0xf8, 0x8e, 0xd1, 0x30, 0x9a, 0x75, 0x66, 0x06,
	0x3e, 0x22, 0x54, 0x82, 0xf8, 0x2c, 0x72, 0xcc, 0x86, 0xd1, 0xac, 0x31, 0xbd, 0x46, 0x07, 0x76,
	0x45, 0xd4, 0x89, 0xa6, 0x21, 0x77, 0xca, 0x0d, 0xa3, 0x59, 0x66, 0x19, 0x44, 0x17, 0x6a, 0x62,
	0x32, 0x49, 0x4b, 0x15, 0x5d, 0x5a, 0x61, 0x24, 0x70, 0x23, 0x88, 0xdf, 0x78, 0x61, 0x30, 0x96,
	0x9e, 0xe2, 0xbe, 0xb3, 0xa3, 0x19, 0x73, 0x7b, 0xe4, 0x05, 0x60, 0xc7, 0xf7, 0x33, 0x31, 0x8c,
	0x7f, 0x4b, 0x78, 0xac, 0xae, 0xa3, 0x89, 0xdc, 0x87, 0x5b, 0x8c, 0xcf, 0xc4, 0x05, 0xdf, 0x32,
	0x4c, 0xee, 0xc2, 0x5e, 0xd6, 0xf2, 0x31, 0xe1, 0xf2, 0xb2, 0xd0, 0xf0, 0x0e, 0x70, 0xc8, 0xd5,
	0x36, 0x0d, 0x36, 0x98, 0x22, 0x53, 0x60, 0x8a, 0x08, 0x6f, 0xc2, 0xce, 0x44, 0xc8, 0xf3, 0xf4,
	0x46, 0x6a, 0x2c, 0x05, 0xe4, 0x87, 0x01, 0x07, 0x1b, 0x64, 0x43, 0xe5, 0xa9, 0x24, 0xc6, 0x47,
	0x50, 0x8d, 0xf5, 0x4a, 0xf3, 0xd9, 0xed, 0xdb, 0xb4, 0xd0, 0x43, 0xd3, 0x0f, 0x5b, 0x36, 0x92,
	0x57, 0x50, 0x5d, 0x0e, 0x5b, 0xb0, 0x3b, 0xec, 0x8d, 0x46, 0xfd, 0xc1, 0xe9, 0x7e, 0x69, 0x01,
	0xbe, 0x74, 0xfa, 0x1a, 0x18, 0xb8, 0x07, 0x75, 0xd6, 0x1b, 0x7d, 0x62, 0x83, 0x05, 0x34, 0xb1,
	0x06, 0x95, 0xb7, 0x67, 0x83, 0xde, 0x7e, 0x99, 0xfc, 0x36, 0xe0, 0x4e, 0x46, 0x9f, 0x5d, 0x76,
	0x20, 0xa2, 0x0f, 0x9e, 0xf4, 0x66, 0x5c, 0x71, 0x19, 0x17, 0x4e, 0xf7, 0x74, 0xed, 0xf0, 0xe2,
	0x88, 0x56, 0xfb, 0x98, 0xa6, 0x21, 0xa2, 0x59, 0x88, 0x68, 0x3f, 0x52, 0xcf, 0x9e, 0x7c, 0xf6,
	0xc2, 0x84, 0xaf, 0xed, 0x7f, 0xbe, 0x61, 0x7f, 0x79, 0xfb, 0xdc, 0x3a, 0x1b, 0xaf, 0xaf, 0x64,
	0xa3, 0xa2, 0x87, 0xdd, 0xc2, 0x70, 0x57, 0x88, 0x30, 0x9d, 0xcd, 0xf5, 0xb7, 0x7f, 0x99, 0x60,
	0xaf, 0x2e, 0x50, 0x3f, 0x0c, 0x6c, 0x81, 0xb5, 0x11, 0x25, 0x3c, 0xa4, 0xc5, 0x60, 0xb9, 0x75,
	0x9a, 0xed, 0x90, 0x12, 0x76, 0xc1, 0xce, 0x27, 0x08, 0x8f, 0xe8, 0x5f, 0x23, 0xe5, 0x1e, 0x15,
	0x74, 0xf5, 0x16, 0xcf, 0x8d, 0x94, 0xf0, 0x01, 0x58, 0xa7, 0x6b, 0x2b, 0xd1, 0xa6, 0xb9, 0xa8,
	0xe5, 0xff, 0xf7, 0x12, 0xac, 0x0d, 0xdb, 0xf1, 0x90, 0x16, 0x53, 0xe7, 0x62, 0x31, 0x19, 0xa4,
	0xf4, 0xd0, 0xc0, 0xf7, 0x70, 0xb0, 0x3a, 0xfd, 0x8a, 0xe1, 0x84, 0xfe, 0xd7, 0xe4, 0x7f, 0xcb,
	0x1e, 0x57, 0xf5, 0xce, 0xe3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32, 0x4e, 0x1f, 0x3b, 0x6c,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BoltlockServerClient is the client API for BoltlockServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoltlockServerClient interface {
	AddBoltlock(ctx context.Context, in *AddBoltlockRequest, opts ...grpc.CallOption) (*Boltlock, error)
	RemoveBoltlock(ctx context.Context, in *RemoveBoltlockRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetBoltlock(ctx context.Context, in *BoltlockQuery, opts ...grpc.CallOption) (*Boltlock, error)
	SetBoltlock(ctx context.Context, in *SetBoltlockRequest, opts ...grpc.CallOption) (BoltlockServer_SetBoltlockClient, error)
	CalibrateBoltlock(ctx context.Context, in *BoltlockCalibrationParameters, opts ...grpc.CallOption) (*empty.Empty, error)
}

type boltlockServerClient struct {
	cc *grpc.ClientConn
}

func NewBoltlockServerClient(cc *grpc.ClientConn) BoltlockServerClient {
	return &boltlockServerClient{cc}
}

func (c *boltlockServerClient) AddBoltlock(ctx context.Context, in *AddBoltlockRequest, opts ...grpc.CallOption) (*Boltlock, error) {
	out := new(Boltlock)
	err := c.cc.Invoke(ctx, "/BoltlockServer/AddBoltlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltlockServerClient) RemoveBoltlock(ctx context.Context, in *RemoveBoltlockRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/BoltlockServer/RemoveBoltlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltlockServerClient) GetBoltlock(ctx context.Context, in *BoltlockQuery, opts ...grpc.CallOption) (*Boltlock, error) {
	out := new(Boltlock)
	err := c.cc.Invoke(ctx, "/BoltlockServer/GetBoltlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boltlockServerClient) SetBoltlock(ctx context.Context, in *SetBoltlockRequest, opts ...grpc.CallOption) (BoltlockServer_SetBoltlockClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BoltlockServer_serviceDesc.Streams[0], "/BoltlockServer/SetBoltlock", opts...)
	if err != nil {
		return nil, err
	}
	x := &boltlockServerSetBoltlockClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BoltlockServer_SetBoltlockClient interface {
	Recv() (*SetBoltlockStatus, error)
	grpc.ClientStream
}

type boltlockServerSetBoltlockClient struct {
	grpc.ClientStream
}

func (x *boltlockServerSetBoltlockClient) Recv() (*SetBoltlockStatus, error) {
	m := new(SetBoltlockStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *boltlockServerClient) CalibrateBoltlock(ctx context.Context, in *BoltlockCalibrationParameters, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/BoltlockServer/CalibrateBoltlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoltlockServerServer is the server API for BoltlockServer service.
type BoltlockServerServer interface {
	AddBoltlock(context.Context, *AddBoltlockRequest) (*Boltlock, error)
	RemoveBoltlock(context.Context, *RemoveBoltlockRequest) (*empty.Empty, error)
	GetBoltlock(context.Context, *BoltlockQuery) (*Boltlock, error)
	SetBoltlock(*SetBoltlockRequest, BoltlockServer_SetBoltlockServer) error
	CalibrateBoltlock(context.Context, *BoltlockCalibrationParameters) (*empty.Empty, error)
}

func RegisterBoltlockServerServer(s *grpc.Server, srv BoltlockServerServer) {
	s.RegisterService(&_BoltlockServer_serviceDesc, srv)
}

func _BoltlockServer_AddBoltlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBoltlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltlockServerServer).AddBoltlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoltlockServer/AddBoltlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltlockServerServer).AddBoltlock(ctx, req.(*AddBoltlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoltlockServer_RemoveBoltlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBoltlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltlockServerServer).RemoveBoltlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoltlockServer/RemoveBoltlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltlockServerServer).RemoveBoltlock(ctx, req.(*RemoveBoltlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoltlockServer_GetBoltlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoltlockQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltlockServerServer).GetBoltlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoltlockServer/GetBoltlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltlockServerServer).GetBoltlock(ctx, req.(*BoltlockQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoltlockServer_SetBoltlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetBoltlockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BoltlockServerServer).SetBoltlock(m, &boltlockServerSetBoltlockServer{stream})
}

type BoltlockServer_SetBoltlockServer interface {
	Send(*SetBoltlockStatus) error
	grpc.ServerStream
}

type boltlockServerSetBoltlockServer struct {
	grpc.ServerStream
}

func (x *boltlockServerSetBoltlockServer) Send(m *SetBoltlockStatus) error {
	return x.ServerStream.SendMsg(m)
}

func _BoltlockServer_CalibrateBoltlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoltlockCalibrationParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoltlockServerServer).CalibrateBoltlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BoltlockServer/CalibrateBoltlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoltlockServerServer).CalibrateBoltlock(ctx, req.(*BoltlockCalibrationParameters))
	}
	return interceptor(ctx, in, info, handler)
}

var _BoltlockServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BoltlockServer",
	HandlerType: (*BoltlockServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBoltlock",
			Handler:    _BoltlockServer_AddBoltlock_Handler,
		},
		{
			MethodName: "RemoveBoltlock",
			Handler:    _BoltlockServer_RemoveBoltlock_Handler,
		},
		{
			MethodName: "GetBoltlock",
			Handler:    _BoltlockServer_GetBoltlock_Handler,
		},
		{
			MethodName: "CalibrateBoltlock",
			Handler:    _BoltlockServer_CalibrateBoltlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetBoltlock",
			Handler:       _BoltlockServer_SetBoltlock_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "boltlockserver/boltlockserver.proto",
}
