// Code generated by protoc-gen-go. DO NOT EDIT.
// source: robotserver/robotserver.proto

package robotserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServoRequest struct {
	RobotId              string   `protobuf:"bytes,2,opt,name=robotId,proto3" json:"robotId,omitempty"`
	Angle                int64    `protobuf:"varint,1,opt,name=angle,proto3" json:"angle,omitempty"`
	Delay                int64    `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServoRequest) Reset()         { *m = ServoRequest{} }
func (m *ServoRequest) String() string { return proto.CompactTextString(m) }
func (*ServoRequest) ProtoMessage()    {}
func (*ServoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_robotserver_2a70260ae6063f47, []int{0}
}
func (m *ServoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServoRequest.Unmarshal(m, b)
}
func (m *ServoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServoRequest.Marshal(b, m, deterministic)
}
func (dst *ServoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServoRequest.Merge(dst, src)
}
func (m *ServoRequest) XXX_Size() int {
	return xxx_messageInfo_ServoRequest.Size(m)
}
func (m *ServoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServoRequest proto.InternalMessageInfo

func (m *ServoRequest) GetRobotId() string {
	if m != nil {
		return m.RobotId
	}
	return ""
}

func (m *ServoRequest) GetAngle() int64 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func (m *ServoRequest) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func init() {
	proto.RegisterType((*ServoRequest)(nil), "ServoRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RobotServerClient is the client API for RobotServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RobotServerClient interface {
	SetServo(ctx context.Context, in *ServoRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type robotServerClient struct {
	cc *grpc.ClientConn
}

func NewRobotServerClient(cc *grpc.ClientConn) RobotServerClient {
	return &robotServerClient{cc}
}

func (c *robotServerClient) SetServo(ctx context.Context, in *ServoRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/RobotServer/SetServo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotServerServer is the server API for RobotServer service.
type RobotServerServer interface {
	SetServo(context.Context, *ServoRequest) (*empty.Empty, error)
}

func RegisterRobotServerServer(s *grpc.Server, srv RobotServerServer) {
	s.RegisterService(&_RobotServer_serviceDesc, srv)
}

func _RobotServer_SetServo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServerServer).SetServo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RobotServer/SetServo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServerServer).SetServo(ctx, req.(*ServoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RobotServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RobotServer",
	HandlerType: (*RobotServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetServo",
			Handler:    _RobotServer_SetServo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "robotserver/robotserver.proto",
}

func init() {
	proto.RegisterFile("robotserver/robotserver.proto", fileDescriptor_robotserver_2a70260ae6063f47)
}

var fileDescriptor_robotserver_2a70260ae6063f47 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0xca, 0x4f, 0xca,
	0x2f, 0x29, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x47, 0x62, 0xeb, 0x15, 0x14, 0xe5, 0x97, 0xe4,
	0x4b, 0x49, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0x79, 0x49, 0xa5, 0x69, 0xfa, 0xa9,
	0xb9, 0x05, 0x25, 0x95, 0x10, 0x49, 0xa5, 0x10, 0x2e, 0x9e, 0xe0, 0xd4, 0xa2, 0xb2, 0xfc, 0xa0,
	0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x09, 0x2e, 0x76, 0xb0, 0x09, 0x9e, 0x29, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x08, 0x17, 0x6b, 0x62, 0x5e, 0x7a, 0x4e, 0xaa,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x84, 0x03, 0x12, 0x4d, 0x49, 0xcd, 0x49, 0xac, 0x94,
	0x60, 0x86, 0x88, 0x82, 0x39, 0x46, 0x4e, 0x5c, 0xdc, 0x41, 0x20, 0x6d, 0xc1, 0x60, 0x77, 0x08,
	0x19, 0x73, 0x71, 0x04, 0xa7, 0x82, 0x39, 0xf9, 0x42, 0xbc, 0x7a, 0xc8, 0xf6, 0x49, 0x89, 0xe9,
	0x41, 0x5c, 0xa7, 0x07, 0x73, 0x9d, 0x9e, 0x2b, 0xc8, 0x75, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x11,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0x86, 0x13, 0x91, 0xde, 0x00, 0x00, 0x00,
}
